-- Generated by scripts/seed-local-images.mjs — review before running
-- Only fills empty image_url for products/categories (won't overwrite admin-uploaded URLs)
-- Projects/gallery updates force local public/ paths from scanned filenames

update public.product_categories set image_url = '/products/roofing-sheets.jpg' where slug = 'roofing-sheets' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/puff-sheets.jpg' where slug = 'puff-sheets' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/decking-sheet-gi.jpg' where slug = 'decking-sheet-gi' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/mangalore-tile-sheet.jpg' where slug = 'mangalore-tile-sheet' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/spanish-tile-sheet.jpg' where slug = 'spanish-tile-sheet' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/liner-sheet.jpg' where slug = 'liner-sheet' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/aluminium-sheet.jpg' where slug = 'aluminium-sheet' and (image_url is null or image_url = '');
update public.product_categories set image_url = '/products/upvc-sheet.jpg' where slug = 'upvc-sheet' and (image_url is null or image_url = '');

update public.products set image_url = '/products/galvalume-roofing-sheets.jpg' where slug = 'galvalume-roofing-sheets' and (image_url is null or image_url = '');
update public.products set image_url = '/products/puff-roof-panel.jpg' where slug = 'puff-roof-panel' and (image_url is null or image_url = '');
update public.products set image_url = '/products/puff-wall-panel.jpg' where slug = 'puff-wall-panel' and (image_url is null or image_url = '');
update public.products set image_url = '/products/gi-decking-sheet.jpg' where slug = 'gi-decking-sheet' and (image_url is null or image_url = '');
update public.products set image_url = '/products/mangalore-tile-profile.jpg' where slug = 'mangalore-tile-profile' and (image_url is null or image_url = '');
update public.products set image_url = '/products/spanish-tile-profile.jpg' where slug = 'spanish-tile-profile' and (image_url is null or image_url = '');
update public.products set image_url = '/products/liner-sheet-product.jpg' where slug = 'liner-sheet-product' and (image_url is null or image_url = '');
update public.products set image_url = '/products/aluminium-sheet-071.jpg' where slug = 'aluminium-sheet-071' and (image_url is null or image_url = '');
update public.products set image_url = '/products/upvc-tile-sheets.jpg' where slug = 'upvc-tile-sheets' and (image_url is null or image_url = '');

-- Projects: actual files under public/projects/
update public.projects set image_url = '/projects/photorealistic_industrial_photography_of_a_large_public_sector_building_under.png' where slug = 'government';
update public.projects set image_url = '/projects/photorealistic_photography_of_a_large_modern_warehouse_exterior_with_a_long.png' where slug = 'warehouse';
update public.projects set image_url = '/projects/photorealistic_photography_of_a_small_modern_commercial_residential_building.png' where slug = 'retail-work-home';
update public.projects set image_url = '/projects/photorealistic_photography_of_a_row_of_retail_storefronts_with_matching_metal.png' where slug = 'shops-franchisee';

-- Gallery: actual files under public/gallery/ (PNG bytes; were misnamed .jpg)
update public.gallery_images set image_url = '/gallery/warehouse-roof.png' where title = 'Warehouse roof package' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/fabrication-panels.png' where title = 'Fabrication panel prep' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/retail-canopy.png' where title = 'Retail canopy finish' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/puff-wall.png' where title = 'PUFF wall cladding' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/mangalore-tile-roof.png' where title = 'Mangalore tile residence' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/decking-mezzanine.png' where title = 'GI decking mezzanine' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/government-cladding.png' where title = 'Government cladding supply' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
update public.gallery_images set image_url = '/gallery/shops-franchisee-cover.png' where title = 'Franchisee roof cover' and (image_url like '/gallery/%' or image_url like '/placeholders/%' or image_url is null);
-- Catch any remaining /gallery/*.jpg pointers after the rename
update public.gallery_images set image_url = replace(image_url, '.jpg', '.png') where image_url like '/gallery/%.jpg';
